### ISSUE TITLE
Remove the special demo and builtin option for the config?

### ISSUE THREAD

**Issue by pmeier** [Quansight/ragna#124]
The original intention was to make it easier for the user to select these two without the need of a config file. However, it is beginning to dawn on me that this actually makes it more confusing:

By having `builtin` as default, starting the worker / API / UI without a config is possible. However, we are only including components for which the requirements are met. So if one does `pip install ragna[builtin]`, they would only see the builtin source storages, since all assistants so far require an API key to be set as environment variable. Worse, if one does `pip install ragna`, the default `builtin` configuration is the same as `demo`, since now we likely not even meet the package requirements.

By removing the `demo` and `builtin` option and in turn require the `-c` / `--config` option, we would "force" users through the config wizard. And by that they should have a better understand what they are running.

**Comment by smeragoel** [comment]
I think that makes sense, since we want them to go through the config to get a better understanding.

**Comment by pmeier** [comment]
Closed in #125.
