### ISSUE TITLE
[ENH] - Ragna as an api proxy for LLMs

### ISSUE THREAD

**Issue by costrouc** [Quansight/ragna#127]
### Feature description

There are several common issue with commercial LLMs via REST api's at the moment:
 - api tokens are hard to scope and create
 - rate limiting access to certain groups/users is impossible
 - monitoring usage
 - queries are expensive and no caching available

I am suggesting a feature of Ragna acting as a traditional proxy:
 - Ragna will delegate tokens (specific to ragna) and internally control the proxying of requests allowing it to do pretty much anything with the request considering we are effectively MITMing the requests.
 
The open ai python client already [supports this use case](https://github.com/openai/openai-python/blob/284c1799070c723c6a553337134148a7ab088dd8/openai/__init__.py#L50) and importantly supports a base path in the url so we could support this via e.g. `my.ragna.url/proxy/openai/` as the base url.

### Value and/or benefit

From an organization perspective this gives a much better:
 -  understanding of usage
 - provides the ability to limit usage granularly
 - avoids passing sensitive api token around which have larger scope than their intended usage by users

**Comment by ishaan-jaff** [comment]
@costrouc LiteLLM has an open source proxy with all the above mentioned features: https://docs.litellm.ai/docs/simple_proxy 

Hope this is useful for your use case

**Comment by pmeier** [comment]
I agree @ishaan-jaff. This is functionality that should live outside of Ragna. Following https://github.com/Quansight/ragna/issues/204#issuecomment-1823655343, maybe we'll have a `ragna-litellm` extension at some point so users can enjoy LiteLLMs features together with Ragna.
