### ISSUE TITLE
Are we using telemetry anywhere? If so this needs to be explicit and opt-in only.

### ISSUE THREAD

**Issue by dharhas** [Quansight/ragna#128]
While setting up my machine for for a development install, I noticed that opentelemetry was one of the dependencies being used. How are we using it and why? Telemetry is a touchy subject and I want to make sure we are clear on this.

**Comment by pmeier** [comment]
> How are we using it and why?

We don't. `chromadb` [does](https://github.com/chroma-core/chroma/blob/f5ee5816647a4bb30d508929bbae174a46d9ae8b/pyproject.toml#L29-L31):

```bash
$ pip install 'ragna[builtin]'
$ pip show opentelemetry-api
Required-by: chromadb, opentelemetry-exporter-otlp-proto-grpc, opentelemetry-sdk
```

They use an opt-out model and that is exactly what we do:

https://github.com/Quansight/ragna/blob/a04efc2fbde3f44d541f6c49f84a92b4c91f2fc4/ragna/source_storages/_chroma.py#L28-L34
