### ISSUE TITLE
[DOCS] - Ragna 101 is not working smoothly

### ISSUE THREAD

**Issue by ahuang11** [Quansight/ragna#144]
### Bug description

I installed using `pip install "ragna[all]"` and scrolled all the way down to the complete script
https://ragna.chat/en/latest/tutorials/python-api/

I think these need to be updated from -> to:
assistant -> assistants
source_storage -> source_storages
path -> document_path

### How to reproduce the bug?

Paste
```
import asyncio

from ragna import Rag
from ragna.assistant import RagnaDemoAssistant
from ragna.source_storage import RagnaDemoSourceStorage


async def main():
    rag = Rag()

    path = "ragna.txt"
    with open(document_path, "w") as file:
    file.write("Ragna is an open-source RAG orchestration app.\n")

    async with rag.chat(
        documents=[document_path],
        source_storage=RagnaDemoSourceStorage,
        assistant=RagnaDemoAssistant,
    ) as new_chat:
        prompt = "What is Ragna?"
        answer = await new_chat.answer(prompt)

    print(answer)


# This is only needed when running module as script.
# If inside a notebook, the code inside the main function can be run directly.
if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by pmeier** [comment]
Thanks for the report @ahuang11!

> I installed using `pip install "ragna[all]"`

For the current release, you need to `pip install "ragna[builtin]"`. We switched the key in #133. Let me switch the website to show the documentation of the latest release instead.
