### ISSUE TITLE
[BUG] - Ragna UI isn't able to help with my prompt

### ISSUE THREAD

**Issue by ahuang11** [Quansight/ragna#145]
### Bug description

I have a file test.txt containing:
```
Ragna is an open-source RAG orchestration app.
```

When I upload that file, I'm surprised that it can't provide a better answer
<img width="600" alt="image" src="https://github.com/Quansight/ragna/assets/15331990/53de0f84-6a27-4599-9203-7c8d63c1089e">

### How to reproduce the bug?

`ragna ui` and upload the txt doc

**Comment by pmeier** [comment]
Closed in #147.
