### ISSUE TITLE
Create release notes for 0.1.1

### ISSUE THREAD

**Issue by pavithraes** [Quansight/ragna#152]
Document changes in `references/changelog.md` before we cut a patch release

**Comment by pavithraes** [comment]
@pmeier - Shall we generate these automatically with GitHub: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes?

**Comment by pmeier** [comment]
Here is automatically generated version for the pre-release: https://github.com/Quansight/ragna/releases/tag/v0.1.1rc0
