### ISSUE TITLE
[BUG] - 500 Internal Server Error Upon Ingestion of Certain Files

### ISSUE THREAD

**Issue by peachkeel** [Quansight/ragna#172]
### Bug description

When ingesting files with filenames containing special characters, particularly '&' and '#', Ragna issues a 500 Internal Server Error via its API. This issue seems to be due to the improper URL encoding of these filenames in the commands that precede file uploading.

### How to reproduce the bug?

echo "Hello! This is a test." > "test&test.txt"

Try to start a new conversation in Ragna UI by upload the "test&test.txt" file.

Log:

INFO:     x.x.x.x:35076 - "OPTIONS /document?name=test&test.txt HTTP/1.1" 200 OK
INFO:     x.x.x.x:35076 - "GET /document?name=test&test.txt HTTP/1.1" 200 OK
INFO:     x.x.x.x:35076 - "POST /document HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:51872 - "POST /chats HTTP/1.1" 500 Internal Server Error

Notice how the '&' is not properly URL encoded in the calls leading up to the first POST. The same thing happens with the hash character (i.e., '#').

### Versions and dependencies used

Ragna v0.1.1

**Comment by pmeier** [comment]
Thanks for the report @peachkeel. We should probably just refactor the `GET /document` endpoint to take the document name as part of the request body rather than as query parameter in the URL:

https://github.com/Quansight/ragna/blob/62098457588cef258f4ea6a8b35989257559a27f/ragna/_api/core.py#L99-L103

**Comment by peachkeel** [comment]
For the record, I was able to patch this problem in v0.1.1 of Ragna. It turns out the `name` parameter wasn't being URL encoded:

https://github.com/Quansight/ragna/blob/3d8541f15ca187b6ef01d49e40db8f33fc9d7ec4/ragna/_ui/resources/upload.js#L9C1-L10C77

Fix:

```python
async function uploadFile(file, token, informationEndpoint) {
    const encodedName = encodeURIComponent(file.name);
    const response = await fetch(`${informationEndpoint}?name=${encodedName}`, {
```
