### ISSUE TITLE
Increase API assistant timeout

### ISSUE THREAD

**Issue by pmeier** [Quansight/ragna#174]
As reported in https://github.com/Quansight/ragna/issues/166#issuecomment-1801813313, 30 seconds timeout might still not be enough. I don't feel we should go to 90 seconds right away, but maybe meet in the middle at 60 seconds first. I have never had a request take more than 30 seconds, so tripling it might be a overkill. Remember that higher timeout also increase the time to signal if there is an actual timeout happening.

Timeout can be adjusted here:

https://github.com/Quansight/ragna/blob/62098457588cef258f4ea6a8b35989257559a27f/ragna/assistants/_api.py#L29

cc @nenb

**Comment by petrpan26** [comment]
Can I take this issue. I saw that Open AI have streaming api, do we want in the future to use this feature to verify that we still waiting for output ?

**Comment by pmeier** [comment]
@petrpan26 I've opened #185 to explain why streaming the response is a lot harder to implement than you might initially think.
