### ISSUE TITLE
Provide a default config if none is supplied

### ISSUE THREAD

**Issue by pmeier** [Quansight/ragna#180]
_originally posted by @nenb in https://github.com/Quansight/ragna/issues/166#issuecomment-1801813313_

- **I replaced the wizard with 'sensible defaults'** - I don't really like having to use a wizard before I start something, I'd much prefer just to have a bunch of 'sensible defaults' that mean I can get started straight away (and I think a lot of users might lose interest if they have to spend mental energy on thinking about init values etc, and might move on). I've tried to tweak the code so that if a TOML file does not exist, then it will just fall back to the default values given to `pydantic`.

**Comment by pmeier** [comment]
We had exactly that not long back. And internal user tests showed that it was confusing, because they did not know how to enable the source storages and mainly the assistants. See #124 for the "discussion" (sorry, happened mostly offline) and #125 for the resolution.

I'm open to have a "shortcut" like `ragna init --default` or the like that avoids going through the wizard and just gives you the config file. But this is another discussion. If you want something like that, please open a separate issue.

**Comment by nenb** [comment]
(@pmeier  I'm continuing the discussion here as I think I did not communicate very clearly. I'm happy to create a new issue if it was in fact clear what I was saying in my original message)

My issue was that I did not want to 'force'  a user to go through the wizard just to use the UI. I think this is generally recognised as a sub-optimal UX (see [here](https://www.chestergrant.com/summary-dont-make-me-think-revisited-steve-krug) for a brief summary of an influential book in this area).

Is there not a middle-ground somewhere that can achieve this eg if no TOML file is found locally, then the CLI just creates one from the sensible defaults in `core/_config.py` and moves on?

**Comment by pmeier** [comment]
We had something like the middle-ground that you are proposing before. By default, the commands would use a configuration that pulled in all source storages and assistants that we available and ran the command. That meant users could start the UI without doing anything, but where surprised when they could select nothing but the demo assistant. When we did internal user testing, I needed to answer the question "How do I enable GPT-4" multiple times.

Our solution to this was to force users to go through the config wizard where they can select the components they want and get instructions on how to meet the requirements. After than you can run `ragna ui` again without setting any configuration file and get what you have selected previously.

I agree that forcing users to do something is not optimal. On the other hand, leaving them in a confused state is worse. Meaning, unless you have a better way to educate users on what they need to do to enable the components they want, we are going to stick to what we have right now.

**Comment by nenb** [comment]
_(I'm happy to leave this for now, but will just make a response to your last comment here in case it's revisited in the future.)_

>When we did internal user testing, I needed to answer the question "How do I enable GPT-4" multiple times.

I would argue that this is an issue with not selecting the most user-friendly defaults (not easy!), rather than anything that requires a wizard. GPT models are so universal now, that I think they need to be included out of the box. This might have been an issue if a user needed to install `openai`, but since they don't need to thanks to the work that has been done on creating a client in `ragna` (nice!), I think this could be solved by just making sure that GPT is always available.

My feeling is that you have to first convince users that it is worth their while investing in something before you can start asking them to invest time in learning

**Comment by pmeier** [comment]
> I would argue that this is an issue with not selecting the most user-friendly defaults (not easy!), rather than anything that requires a wizard. GPT models are so universal now, that I think they need to be included out of the box. This might have been an issue if a user needed to install `openai`, but since they don't need to thanks to the work that has been done on creating a client in `ragna` (nice!), I think this could be solved by just making sure that GPT is always available.

I think you are missing one key point here: users *must* set the `OPENAI_API_KEY` before they can use any GPT model. Providing the assistant it as default does not work without user doing something. And to reiterate, this was the issue that most internal users hit during testing. They simply were not aware that they had to set and environment variable much less which one.

Meaning, there is nothing we can do on Ragna side to

> making sure that GPT is always available.

The only option we have is to somehow educate users to do it. And the best way we found is to force them through the config wizard. With that, they have it spelled out what to do.

> My feeling is that you have to first convince users that it is worth their while investing in a tool before you can start asking them to invest time in learning how to use it.

I agree with that in general. What would be your suggestion on how to educate users on how to meet the requirements?
