### ISSUE TITLE
[BUG] - Package imports take an unusually long time to complete

### ISSUE THREAD

**Issue by nenb** [Quansight/ragna#181]
### Bug description

_(This is somewhere between a bug and a feature request._:shrug:_)_

If I run a CLI command (eg `ragna ui`), it takes quite a while before the package imports are complete. Part of this seems to be related to the customised import system (eg `PackageRequirement.is_available`). 

### How to reproduce the bug?

`python -X importtime -m ragna 2> import.log` will give some nice insights (perhaps with a profile viewer like [tuna](https://github.com/nschloe/tuna)).

I'm still familarising myself with the logic of the import system, but what I have noticed is that a lot of time is spent in `PackageRequirement.is_available`. In particular, `importlib_metadata_package_distributions().items()` takes a long time to generate and consume. It would be useful to cache this if possible. (I don't believe that the current `functools.cache` is terribly useful, as it is keyed on the instance, rather than the package name.)

### Versions and dependencies used

ragna 0.1.1
CPython 3.9.18
OS Ubuntu 22.04.1

### Anything else?

Is it possible to use a simpler import system eg explicit `import foo` statements inside a `try ... except` block, rather than the `PackageRequirement` hierarchy? Reducing this complexity would make it a bit easier to understand the core logic, and perhaps better understand if the import time can be reduced a lot or a little.

**Comment by pmeier** [comment]
I haven't profiled myself, but if `importlib_metadata_package_distributions` is actually a significant factor, we could certainly cache it. Could you post some results with and without caching?

The reason we have this more complicated logic is that the distribution and package name not always match up. For example, for PDF parsing we require

https://github.com/Quansight/ragna/blob/62098457588cef258f4ea6a8b35989257559a27f/ragna/core/_document.py#L248-L250

but after that is installed, one needs to import

https://github.com/Quansight/ragna/blob/62098457588cef258f4ea6a8b35989257559a27f/ragna/core/_document.py#L259-L263

`importlib_metadata_package_distributions` is the link between the two.

**Comment by pmeier** [comment]
Had a quick stab at this. It seems that you are right and `importlib_metadata_package_distributions` does some have path operations. I have super fast file system, but even there the difference is notable:

```python
import cProfile
from ragna.core import PdfDocumentHandler
from ragna.source_storages import Chroma, LanceDB

with cProfile.Profile() as pr:
    for component in [PdfDocumentHandler, Chroma, LanceDB]:
        component.is_available()

pr.print_stats(sort="tottime")
```

### without caching

```
         10896011 function calls (10847165 primitive calls) in 3.746 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   185933    0.459    0.000    0.668    0.000 pathlib.py:64(parse_parts)
    96194    0.274    0.000    0.406    0.000 {built-in method posix.stat}
   185933    0.187    0.000    0.888    0.000 pathlib.py:682(_parse_args)
      352    0.115    0.000    1.997    0.006 __init__.py:507(skip_missing_files)
     5270    0.096    0.000    0.527    0.000 feedparser.py:218(_parsegen)
```

### with caching

```
         2916942 function calls (2868096 primitive calls) in 1.150 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1099    0.121    0.000    0.121    0.000 {built-in method marshal.loads}
     4035    0.052    0.000    0.052    0.000 {method 'sub' of 're.Pattern' objects}
     2574    0.047    0.000    0.250    0.000 feedparser.py:218(_parsegen)
   194903    0.045    0.000    0.052    0.000 feedparser.py:78(readline)
    92/89    0.038    0.000    0.040    0.000 {built-in method _imp.create_dynamic}
```

Meaning, caching actually reduces the number of function calls by roughly 4x and shaves off roughly 2.5 seconds. The latter is probably even more pronounced on slower file systems.

**Comment by nenb** [comment]
Thanks for doing all this profiling and documentation, you did all the work for me! FYI, The latest version is a big difference for me in terms of usability (I guess my hardware specs are quite a bit different to yours), thank you!

>The reason we have this more complicated logic is that the distribution and package name not always match up.

My original comment was actually related to classes like `PackageRequirement` and methods like `is_available`. Naively, I would expect that most of this class hierarchy could be replaced with some hardcoded import statements dotted through the code, perhaps along with some `try ... exception` blocks to tell the user that a package is missing. My current feeling is that the current import system adds quite a bit of complexity to the code (as well as some overhead), and I'm still not entirely sure why it's needed (although this is likely down to ignorance on my part!)

**Comment by pmeier** [comment]
Of course we could just have a simple `try` / `except` block everywhere. But this would mean we cannot check if the requirements are available without actually trying to instantiate the class. With the `Requirement` subclasses and the standardized `.requirements()` and `.is_available()` class methods, it is easy to implement the config wizard or automatically register the builtin document handlers. Plus, it allows us something like automatically documenting requirements for every component by writing a hook that attaches a standardized message to each docstring. Meaning, it definitively has its use case.

> My current feeling is that the current import system adds quite a bit of complexity to the code (as well as some overhead)

Yes, it adds complexity for the Ragna maintainers, but it reduces complexity for someone writing a new component. In the latter use case, one only needs to add a `PackageRequirement` and after that can be sure that this package with its version constraints is available at runtime without any further configuration.

Try approaching this from the other side: how would you write a manual check for

https://github.com/Quansight/ragna/blob/dc497ef4768b8f8bd4d5c3736eb1d67b27050387/ragna/core/_document.py#L250

Maybe

```python
try:
    import fitz

    if tuple(map(int, fitz.__version__.split("."))) < (1, 23, 6):
        raise ModuleNotFoundError
except ModuleNotFoundError:
    print("Please install pymupdf>=1.23.6")
```
? That is way harder. Plus, we only have a simple constraint here. Imagine I throw in something like `pymudpdf >=1.23.6, != 1.24.0, < 2`.
