### ISSUE TITLE
Change the default queue implementation something other than memory

### ISSUE THREAD

**Issue by pmeier** [Quansight/ragna#183]
_originally reported by @nenb in https://github.com/Quansight/ragna/issues/166#issuecomment-1801813313_

- **I changed the default queue implementation from 'memory' to 'file'** - (I'm curious why 'file' was offered over `sqlite` here?). The main reason I did this is that the 'memory' implementation is currently blocking (see [here](https://github.com/Quansight/ragna/blob/62098457588cef258f4ea6a8b35989257559a27f/ragna/core/_queue.py#L148)) and this was a bit of a frustrating experience for me when OpenAI was taking almost 60 seconds sometimes to respond. I'm not familiar enough with `huey` to know if the in-memory implementation can also be adapted to work in async mode (probably not I guess), so I just changed the default setting to 'file' and things went much more smoothly.

**Comment by pmeier** [comment]
> I'm curious why 'file' was offered over sqlite here?

That is a good question and one that I have no answer for. I honestly don't recall why we didn't went for that over file system queue. I'm ok with just swapping the two. The only requirement that we had was that we wanted to have a persistent queue that doesn't require any additional setup. But sqlite certainly fulfills that.

> The main reason I did this is that the 'memory' implementation is currently blocking (see [here](https://github.com/Quansight/ragna/blob/62098457588cef258f4ea6a8b35989257559a27f/ragna/core/_queue.py#L148)) and this was a bit of a frustrating experience for me when OpenAI was taking almost 60 seconds sometimes to respond. I'm not familiar enough with `huey` to know if the in-memory implementation can also be adapted to work in async mode (probably not I guess)

Indeed a memory queue is blocking and this is by design (in huey as well as Ragna). The point here is to enable debugging, which just gets a lot harder if you always operate with a worker running multithreaded in another process. 

Plus, you need to have a worker running if you use a non-memory queue. And this is not acceptable when just using the Python API.

> I just changed the default setting to 'file' and things went much more smoothly.

One option here could be to just use file system (or better sqlite) queue for the API / UI. Both issues mentioned above or not relevant there. So solution could be to just set these values in 

https://github.com/Quansight/ragna/blob/62098457588cef258f4ea6a8b35989257559a27f/ragna/_cli/config.py#L122-L123

rather than using the default Python config. With the same reasoning, we could also make the state persistent by default

https://github.com/Quansight/ragna/blob/62098457588cef258f4ea6a8b35989257559a27f/ragna/core/_config.py#L63

**Comment by nenb** [comment]
I've included some further context/information on this issue below. Unfortunately I can't offer a single suggestion. Instead, I've written up a couple of possible pain-points. I would be happy to help contribute to any of these that may be considered relevant, and to move them to a separate issue if necessary. (Thanks for your patience in allowing me to document all these issues!):

- **`await` does not do what I expect in memory-mode** - I think the `await` syntax is confusing for 'memory' mode. For example, if I want to use `ragna` as a library for my web-server app, when I see a function like `async def answer(self, prompt: str): ...`, I would assume that it's not blocking. But this is not the case for memory mode (the current default).

- **progress bar is probably important for Jupyter notebooks** - I understand why memory mode might need to be the default for the Python API (running a consumer is just another piece of complexity for the average user like me). But given that some of the operations can be compute-intensive (eg embed this bunch of arXiv pdfs that I haven't had time to read yet!) I think that there needs to be some sort of progress bar (eg `tqdm`) to let the user know what's happening, and how much longer they have to wait. I know that not everyone is a fan of these types of tools, but my experience has been that they are very widespread in the field now, especially for the use-case of experimenting in a Jupyter notebook.

- **queues other than memory don't play well with Python API** - If file (or `sqlite`) is used as the default queue, then I just realised that this might interfere with the Python API. For example, if I try and run something like this [demo](https://github.com/Quansight/ragna-presentations/blob/main/rags-to-riches.ipynb) with a filesystem queue, everything will hang until I remember to run the consumer. 

Ultimately, it feels to me like use-cases can be divided into at least two clear groups, that are somewhat orthogonal to each other:

1. **Jupyter notebook experimentation:** I probably don't want to run a consumer, I probably want progress updates on my long-running blocking calculations, I probably don't want `await` syntax (and if I do, I expect it to be non-blocking).
2. **RAG app deployment:** I probably want to be thinking about consumers, it's less likely that I want progress updates in my logs, I definitely want `await` syntax and for it to be non-blocking.

I think it's tricky trying to describe these two use-cases behind a single API, without a bunch of special-casing and extra maintenance. But maybe it's worth it. :thinking:

**Comment by pmeier** [comment]
I agree with most of what you have written down. Some comments:

- I feel the same about using async stuff together with the default memory queue. It just feels off. One option could be to prefix the current methods with an "a", e.g. `.prepare()` -> `.aprepare()` and implement a synchronous version under the old name that calls this. So roughly

  ```python
  class Chat:
      def prepare(...):
          return asyncio.run(self.aprepare(...))
  
      async def aprepare(...):
          # current implementation here
          return ...
  ```
  
  That way, we would still be able to call the async methods from the API, but by default it is clear to the user of the Python API that these calls are blocking. Thoughts?
- I'm not sure about progress bars. I mean, I do like them as indicator that something is done, but where would you want to have some? Progress bar makes sense if you have something to iterate over, but there is nothing like that in Ragna. Unless you are talking about streaming the LLM answer. In which case, let's keep the discussion in #185. If that is resolved to enable streaming, adding a progress bar should be trivial.

**Comment by nenb** [comment]
I'll start with the easier question first!

> I'm not sure about progress bars. I mean, I do like them as indicator that something is done, but where would you want to have some?

For preparing (chunking, pre-processing and in particular embedding) the documents. This is why the queue exists in the first place, right? I view the progress bars as useful wherever the queue is used in the multi-threaded/process version.

>That way, we would still be able to call the async methods from the API, but by default it is clear to the user of the Python API that these calls are blocking. Thoughts?

Yeah, that interface does seem fairly widespread now (eg `openai` package) and is probably what the average user like me is expecting. How would you prevent a user from using `aprepare(...)` in memory-mode? Throw a warning or exception?

**Comment by pmeier** [comment]
> For preparing (chunking, pre-processing and in particular embedding) the documents.

You mean like as part of the actual loops that run inside the components, e.g.

https://github.com/Quansight/ragna/blob/dc497ef4768b8f8bd4d5c3736eb1d67b27050387/ragna/source_storages/_chroma.py#L51-L52

? Any progress bar on a worker cannot be streamed back (same issue as #185) back to the main process. So the only use case is for the synchronous approach. But that means, we need to have some logic on the components to differentiate between the queue type.

One option could be to add a `.tqdm` attribute

https://github.com/Quansight/ragna/blob/dc497ef4768b8f8bd4d5c3736eb1d67b27050387/ragna/core/_components.py#L36-L37

that depending on the queue type either actually is a progress bar wrapper or just a noop. That way, we could always wrap all iterables in `self.tqdm` and don't need to think about it any further.

Just note that something like `self._chunk_pages` currently returns an iterator. Meaning, the progress bar would just indicate that something is done, but can't give you an estimate on how long it'll take, since the length is unknown prior to exhaustion.

As a last thought, I know that `rich` has some progress bar functionality as well. And since we already hard-depend on it, I would prefer that over `tqdm` to avoid an extra dependency.

> How would you prevent a user from using `aprepare(...)` in memory-mode? Throw a warning or exception?

Exception is excessive since it'll ultimately work. I would throw a warning telling the user that although they are using an async function, everything is still blocking.
