### ISSUE TITLE
[BUG] - lancedb retrieval unlikely to be working as expected

### ISSUE THREAD

**Issue by nenb** [Quansight/ragna#193]
### Bug description

When using `lancedb` as `source_storage`, the `retrieve` method is currently implemented as a simple [filter](https://github.com/Quansight/ragna/blob/dc497ef4768b8f8bd4d5c3736eb1d67b27050387/ragna/source_storages/_lancedb.py#L101-L105) rather than a similarity search. This is unlikely to be the behaviour a user is expecting eg if I have 100 documents stored, then the default settings will return the same 4 documents as context for all of my questions.

### How to reproduce the bug?

(Apologies for the 'pseudocode')

1. Create N documents and put some private information that is not available to an LLM in the N'th document.
2. Make sure that the limit in the `_lancedb.py` is set to at most N-1
3. Ask the LLM some a question on the private information
4. The LLM (should!) respond by saying that it couldn't find any information in the sources

### Versions and dependencies used

`ragna` 0.1.1

### Anything else?

I think that the `pylance` package is arguably more relevant as an extension than `lancedb`. `lancedb` contains a lot of extra functionality that I think `ragna` already implements. This might help slim down the size/complexity of the Python environment a bit.

**Comment by pmeier** [comment]
Our implementation follows the official documentation: https://lancedb.github.io/lancedb/search/#search

![image](https://github.com/Quansight/ragna/assets/6849766/3dc06d9a-07b4-4a97-9c2d-b1838f998768)

Let me see if I can reproduce your issue.

**Comment by pmeier** [comment]
Ok, I can somewhat reproduce this. What I'm currently missing a measure of the relevancy of the source, i.e. the distance to the prompt. We need to see that to be able to draw any conclusions of what is happening. I'm also wondering if this is similar to #160.

**Comment by nenb** [comment]
The current implementation does not compute an embedding for the query (perhaps this is what you have just written, apologies if so). This needs to be done and then passed to lance. I can add more details over the weekend at some point.

**Comment by pmeier** [comment]
> The current implementation does not compute an embedding for the query

Worse, the implementation didn't even pass a query :facepalm: Should be fixed now.
