### ISSUE TITLE
Add support for markdown documents

### ISSUE THREAD

**Issue by pmeier** [Quansight/ragna#210]
Markdown is the base format for tools like [Obsidian](https://obsidian.md/) or [logseq](https://logseq.com/). As a user, I would like to be able to ask question about all the notes I took.

Since we already support parsing plain `.txt` files with 

https://github.com/Quansight/ragna/blob/4962665828c51bc6ef0f2d772574f08caec547a8/ragna/core/_document.py#L226-L231

we could just rename it to `PlainTextDocumentHandler` and add `.md` to the supported suffixes.

**Comment by paskett** [comment]
I'd like to help contribute to ragna. This seems like some low-hanging fruit as a first issue and to set up my development environment.
