### ISSUE TITLE
Some classes which contain CPU-intensive methods are not serialisable (pickle)

### ISSUE THREAD

**Issue by nenb** [Quansight/ragna#216]
A list of some classes in `ragna` that can't be pickled, with some possible workarounds. These classes all contain CPU-intensive methods, and so serialisation to another process may be desirable in the future. This initially came up during some experimentation with `anyio`, which uses `pickle`. This list isn't necessarily comprehensive. I also don't consider any of the items to be a bug/blocker (at least for now). I'm happy to contribute to any items that are considered relevant.

 **Issue 1** -  `VectorDatabaseSourceStorage`
 When this class is initialised, it currently sets the `_embedding_function` attribute as `chromadb.utils.embedding_functions.DefaultEmbeddingFunction()`. Unfortunately, `DefaultEmbeddingFunction()` contains a module as an attribute, and hence can't be pickled.
 
 **Possible solutions** 
 1. Defer initialising `DefaultEmbeddingFunction` until inside methods like `store` or `retrieve`.
 2. Work upstream with `chromadb` to see if this attribute really needs to be a module.
 3. Work upstream with `anyio` to see if they might consider using `cloudpickle` instead of `pickle`.

**Comment by nenb** [comment]
**Issue 2** -  `VectorDatabaseSourceStorage`
 When this class is initialised, it currently sets the `_tokenizer` attribute as `tiktoken.get_encoding("cl100k_base")`. Unfortunately, ``tiktoken.Encoding` can't be pickled in its current implementation.
 
 **Possible solutions** 
 1. A PR has been opened [here](https://github.com/openai/tiktoken/pull/181) that should resolve the issue when merged.

**Comment by nenb** [comment]
**Issue 3** - `Chroma`
When this class is initialised, it currently sets the `_client` attribute using an instance of `chromadb.Client`. Unfortunately, with the current settings for Chroma, this creates a SQLite connection,  which can't be serialised.

**Possible solutions**

1. Defer the instantiation of the client to inside of `store` or `retrieve`. It seems to be [cached](https://github.com/chroma-core/chroma/blob/3d399cd0ef89bb2ebb09b35fbad2dd5e46ac727f/chromadb/api/client.py#L114-L119) in the Chroma code, so this might actually be too much overhead.
2. Think of a nicer way of fitting this into the `ragna` code!
3. Consider using a different client from Chroma whose connection is serialisable (but I'm not sure how realistic this is, and `sqlite` fits well with the other parts of `ragna` IMO)

**Comment by pmeier** [comment]
Thanks for the issue @nenb. Indeed having everything serializable is quite a problem. In fact, we basically had what you are suggesting (at least what can be done on our side), but we migrated away from that in #54 for simplicity.

Task queue libraries also usually don't use subprocesses for this exact reason.

My preferred way of handling this is to

1. Wait with any implementation until user demand materializes. Everything else is premature optimization.
2. If there is actual user demand, instead of running CPU bound operations as subprocesses, reinstate the task queue and corresponding workers for that.

**Comment by nenb** [comment]
@pmeier Thanks for the extra information. I'm closing this as your answer has fully documented the situation, but please re-open if you wish.
