### ISSUE TITLE
[ENH] - Add support for .doc / .docx

### ISSUE THREAD

**Issue by pmeier** [Quansight/ragna#225]
### Feature description

Word documents are everywhere in the corporate world. We should support them out of the box. There are multiple Python packages out there that provide this functionality. We should do a light comparison of them to get a clearer picture. Optimally, we find a package that can give us page information. Not sure if that is possible in these data formats though.

### Value and/or benefit

Users with corporate documents will have a lower barrier of entry. Requested in https://github.com/Quansight/ragna/issues/224#issuecomment-1838864057.

**Comment by paskett** [comment]
I would like to work on this issue this week. I looked at three Python packages to read .docx files:

1. [python-docx](https://github.com/python-openxml/python-docx)
2. [docx2python](https://github.com/ShayHill/docx2python)
3. [aspose-words](https://github.com/aspose-words/Aspose.Words-for-Python-via-.NET)

My preference would be 1. -> 2. -> 3. `python-docx` (1.) has been around a long time, has a large user-base, and is being maintained. It seems like the most likely to stick around for a long time. `docx2python` is a smaller project, but may have a more convenient API because it has easy methods for converting directly to text. `aspose-words` (3.) says it supports more formats than just docx, like html, rtf, and epub/mobi. But, it looks like you may need a license to use it, so I think it's out.

I'd like to add `python-docx` as a dependency, but want buy-in from maintainers before I start adding it.

@pmeier you said that it would be nice to have page information. How do you envision that being used?

**Comment by pmeier** [comment]
Thanks @paskett for the survey!

> `docx2python` is a smaller project, but may have a more convenient API because it has easy methods for converting directly to text.

If it doesn't offer anything over `python-docx`, I think a better API is not a high priority. We won't be doing anything but extract text and when we have figured that out once, it is unlikely that we'll ever change that.

That being said, just because it is a smaller project, we shouldn't discard it. The repo seems active as well.

Would you happen to have a docx document that you could run some quick benchmarks to see if there are any performance differences between the two? If no, is there any indication that one might be more performant than the other?

If everything else is basically equal, I would prefer the package with the better API, i.e. `docx2python`.

> `aspose-words` (3.) says it supports more formats than just docx, like html, rtf, and epub/mobi. But, it looks like you may need a license to use it, so I think it's out.

Yep, certainly. We need to stay fully open source in all our dependencies.

> I'd like to add `python-docx` as a dependency, but want buy-in from maintainers before I start adding it.

We'll only add it as optional dependency that will be pulled in when you `pip install 'ragna[all]'`. This process is automated and you only need to declare it as requirement of the `DocumentHandler` like we do for our pdf handler:

https://github.com/Quansight/ragna/blob/18a6a25d05fb2dc6db7be7a371849835a0e495cd/ragna/core/_document.py#L254-L256

After that you just run [this script](https://github.com/Quansight/ragna/blob/18a6a25d05fb2dc6db7be7a371849835a0e495cd/scripts/update_optional_dependencies.py). Optionally, you can add it manually in

https://github.com/Quansight/ragna/blob/18a6a25d05fb2dc6db7be7a371849835a0e495cd/pyproject.toml#L53-L61

> it would be nice to have page information. How do you envision that being used?

We are using it as part of the source view in the UI to make it easier for the user to find the source in the original document.

![image](https://github.com/Quansight/ragna/assets/6849766/fdc101e2-f29c-4755-86ca-8a6eb3df76f0)

Of course, not all formats support page information and I honestly don't know if docx does. In hindsight that is likely not the case, given that tweaking the underlying xml can completely change the layout. Meaning, any page information inside the xml would need to be dynamically computed. Unless you find something in the APIs of the packages that proves me wrong here, I would worry about this for now.

**Comment by paskett** [comment]
Just did some benchmarking on both libraries for four different docx files.

This was all on a mac using timeit and memory_profiler.

`python_docx` is generally about 2-3x faster:
```
Doc 1 -- number = 10 -- 195 pg (216K)
  python_docx 3.96 s
  docx2python 12.84 s
Doc 2 -- number = 100 -- 9 pg (1.3M)
  python_docx 2.92 s
  docx2python 6.91 s
Doc 3 -- number = 100 -- 1 pg (19K)
  python_docx 0.54 s
  docx2python 1.17 s
Doc 4 -- number = 100 -- 13 pg (447K)
  python_docx 1.32 s
  docx2python 4.55 s
``` 

For memory usage, `python_docx` tends to be a little more memory efficient, especially on the longer document I tried with 195 pages:
```
Doc 1 -- number = 1 -- 195 pg (216K)

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    10   28.828 MiB   28.828 MiB           1   @profile
    11                                         def read_docx_python_docx(file):
    12   64.031 MiB   35.203 MiB           1       doc = Document(file)
    13   65.016 MiB    0.750 MiB        9661       text = '\n'.join(x.text for x in doc.iter_inner_content() if not isinstance(x, Table))
    14   64.781 MiB   -0.234 MiB           1       return text

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    16   64.781 MiB   64.781 MiB           1   @profile
    17                                         def read_docx_docx2python(file):
    18   64.781 MiB    0.000 MiB           1       with docx2python(file) as content:
    19  197.531 MiB  132.750 MiB           1           text = content.text
    20  197.531 MiB    0.000 MiB           1       return text
```

Document 2, 3, and 4 they're almost the same (I'll copy just Doc 4 below):
```
Doc 4 -- number = 1 -- 13 pg (447K)

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    10   28.609 MiB   28.609 MiB           1   @profile
    11                                         def read_docx_python_docx(file):
    12   31.234 MiB    2.625 MiB           1       doc = Document(file)
    13   31.266 MiB    0.031 MiB         175       text = '\n'.join(x.text for x in doc.iter_inner_content() if not isinstance(x, Table))
    14   31.266 MiB    0.000 MiB           1       return text

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    16   31.266 MiB   31.266 MiB           1   @profile
    17                                         def read_docx_docx2python(file):
    18   31.266 MiB    0.000 MiB           1       with docx2python(file) as content:
    19   37.031 MiB    5.766 MiB           1           text = content.text
    20   37.031 MiB    0.000 MiB           1       return text
```

I'm happy to add support for `python_docx` and submit a PR.

**Comment by pmeier** [comment]
Awesome, thanks a ton for the benchmarks @paskett! I've just checked and both have the same dependencies as well. So all clear on that front as well.

> I'm happy to add support for `python_docx` and submit a PR.

Go for it! Ping me there for review.
