### ISSUE TITLE
Chat info button displays wrong assistant

### ISSUE THREAD

**Issue by pmeier** [Quansight/ragna#229]
### Bug description

Per title, However, the selected assistant is correctly shown in the side bar when clicking the button.

### How to reproduce the bug?

Select an assistant that is not the default one and start the chat.

### Versions and dependencies used

0.1.2rc0

### Anything else?

![image](https://github.com/Quansight/ragna/assets/6849766/caab680c-a681-4805-b5f1-b9b05abd30c7)

**Comment by pmeier** [comment]
This is defined at

https://github.com/Quansight/ragna/blob/b2730f1dd2b7285a13301cb3e8a7936eca7bd0bb/ragna/deploy/_ui/central_view.py#L613-L615

**Comment by pmeier** [comment]
Ok, repro above is wrong. The value is stuck on whatever you select first. Meaning, if the first chat is `AssistantA | SourceStorageB`, all other chats will also have this label regardless of what components you select.

**Comment by pmeier** [comment]
I'm not sure what is happening here, but as pointer for the future. The `button_name` variable holds the correct value even for the second and other later chats. For whatever reason, it is not accepted though.

**Comment by nenb** [comment]
@pmeier I've just looked into this and I think #252 should fix this (it works locally for me at least).

**Comment by pmeier** [comment]
Closed in #252.
