### ISSUE TITLE
don't return the full chat object on the prepare and answer endpoints of the REST API

### ISSUE THREAD

**Issue by peachkeel** [Quansight/ragna#242]
### Feature description

I've noticed that the `/chats/{id}/answer` endpoint returns both the latest `message` and the full `chat`:

https://github.com/Quansight/ragna/blob/1e256e935e2cb851d686882afd5377002ca011aa/ragna/_api/core.py#L210-L227

I thought that maybe the UI needed all that state about the chat for some distributed system reason, but it looks like it does not:

https://github.com/Quansight/ragna/blob/1e256e935e2cb851d686882afd5377002ca011aa/ragna/_ui/central_view.py#L361-L369

Assuming there is a need to maintain API backward compatibility, could we add a `/chats/{id}/quick_answer` endpoint to Ragna that only returns a `schemas.Message` object as opposed to a heavyweight `schemas.MessageOutput` object?

### Value and/or benefit

Every call to `/chats/{id}/answer` appends another message to the chat. This means that each time the endpoint is called, the amount of data that needs to be sent over the wire increases. Over time, this O(m) growth makes getting answers more and more sluggish. Ideally, the `/chats/{id}/answer` endpoint would be O(1) from a messages in the chat perspective. The proposed `/chats/{id}/quick_answer` endpoint would act in that constant time/space manner.

**Comment by pmeier** [comment]
Thanks @peachkeel for opening this. I agree and had the task of opening an issue about this in my backlog. I'm hitting the same in https://github.com/Quansight/ragna/issues/185#issuecomment-1840399070 in a worse way. TBH, this was a premature optimization. We should remove it.

The only upside for client in always returning the chat is that they don't have to track it. But this is only one API call away, so I guess this ok. Maybe later there is an actual use case, but we don't need to care right now.

**Comment by peachkeel** [comment]
@pmeier,

You're welcome regarding opening the issue. And thank you for getting v0.1.2 out and being such an active maintainer!

One thing I want to bring up related to this issue is that the `Source` class has a `content` attribute:

https://github.com/Quansight/ragna/blob/1e256e935e2cb851d686882afd5377002ca011aa/ragna/core/_components.py#L85-L94

The corresponding `schemas.Source` class does not have this attribute:

https://github.com/Quansight/ragna/blob/1e256e935e2cb851d686882afd5377002ca011aa/ragna/_api/schemas.py#L35-L39

Thus, `schemas.Message` objects coming from the `/chats/{id}/answer` endpoint are missing some relevant info about the contexts used to generate answers.

Maybe this problem should be a separate issue, but I wanted to bring it up here since we're talking about changing the API.

**Comment by pmeier** [comment]
> The corresponding `schemas.Source` class does not have this attribute:

This is intentional and warrants a separate issue. TL;DR: when "live answering" we have access to the source content and thus could just send it back to the client. However, this doesn't work when we are recreating the chat from our state database unless we also store the source content inside the database.
