### ISSUE TITLE
Make it easy to get first impression of Ragna

### ISSUE THREAD

**Issue by MarcSkovMadsen** [Quansight/ragna#243]
### Feature description

I would like to add a short description and a link to Ragna from Panel-Chat-Examples.

The best thing for me would to have

- A Screenshot of the UI in action showing some of the key features.
- A 30 sec video or gif quickly telling what RAGNA is.

It would be natural to add the to your README or Documentation.

### Value and/or benefit

It will help you communicate what Ragna is, feels and looks like.

### Anything else?

In general I think visuals like screenshots or short videos/ gifs a missing from the documentation making it hard to quickly determine if this is "something for me". For example when I go to the README I don't get a quick impression if this is "appealing" to me and how easy it is to get started.

**Comment by pmeier** [comment]
Thanks for the suggestion. Could you explain why you would want to have a screen shot *and* and a GIF? What benefit does the screenshot offer over the GIF?

**Comment by pmeier** [comment]
We also need to solve #247 before we go for a solution here.

**Comment by MarcSkovMadsen** [comment]
> Thanks for the suggestion. Could you explain why you would want to have a screen shot *and* and a GIF? What benefit does the screenshot offer over the GIF?

I was referring to what would be beneficial to add to you README based on my experience promoting Panel and other frameworks.

A screenshot and a gif serves different purposes when communicating. Sometimes technically you can share one and not the other.

**Comment by dharhas** [comment]
So I agree with @MarcSkovMadsen here. I've recently had to show Ragna during calls with folks and not having a screenshot and gif readily available has impacted visibility. I'm currently using a gif I have in my PyData NYC jupyter notebook.

**Comment by Tengal-Teemo** [comment]
@pmeier I am interested to put something together for this.  I'm interested in putting together a 30 second video just showing what ragna does/its core philosophy and showing the CLI and UI (and how quick it is to set up).  The video would not be voiced over, rather information would be conveyed through text so could easily be ported to a gif.  With regard to #247, as a video it could be hosted externally on Youtube and linked here in the documentation, that way it wouldn't have to be here forever.  Let me know if I'm missing anything.

**Comment by Tengal-Teemo** [comment]
https://youtu.be/96XudYti1RA[https://youtu.be/96XudYti1RA](url) is a short video I made attempting to outline of the basics of Ragna's capabilities.  I'm open to feedback, as I understand that there might be a different perspective from somebody who didn't make the video @pmeier @MarcSkovMadsen.  I can make whatever changes are required.

**Comment by MarcSkovMadsen** [comment]
To me this looks great. This could catch my attention.

The next question for me would then be how can I most easily try this out quickly?

**Comment by Tengal-Teemo** [comment]
If I wanted to try out Ragna quickly, best place for me to go would probably be to [install](https://ragna.chat/en/stable/install/) and then [this](https://ragna.chat/en/stable/tutorials/web-app/) page.  I will see if I can work this into the end card.

**Comment by pavithraes** [comment]
@Tengal-Teemo That video looks great, thank you for working on it! 🌻 

> If I wanted to try out Ragna quickly, best place for me to go would probably be to [install](https://ragna.chat/en/stable/install/) and then [this](https://ragna.chat/en/stable/tutorials/web-app/) page. I will see if I can work this into the end card.

I agree, these docs pages will make good call-to-actions :)

It might be nice to keep the "Open Source RAG _Orchestration_ Framework" tagline consistent across various Ragna spaces, so I have a mild preference to using that in the start and end cards. It's only a minor/optional suggestion, the video is quite nice as-is :)

**Comment by pmeier** [comment]
What are we going to do about ownership? Right now, we (Ragna) don't have access to the video file and it is hosted under a YT channel we don't control. Should we have our own YT channel (or whatever other platform we prefer) and host it there?

**Comment by dharhas** [comment]
We have a Quansight YouTube channel we can put it on.

**Comment by Tengal-Teemo** [comment]
@dharhas I can send you the source files for the video, it is made with Davinci resolve, I just need to check all the source video files to make sure that they don't contain any sensitive information.  How can I send it to you?  Once I've implemented the changes suggested by @pavithraes you can upload it.  Thanks for the feedback everyone :)

**Comment by pmeier** [comment]
You can send it to `pmeier at quansight dot com`. I'll distribute it to whoever has access to the YT channel. Thanks a ton for the effort @Tengal-Teemo!

**Comment by Tengal-Teemo** [comment]
@pmeier I have sent you the video with the tagline consistent and some links to the ending.  However, I cannot send the source files as they are ~40GB.  To be honest, any changes that you might want to make could probably just be spliced into the video with the editing software of your choice, so I hope it will be fine.
