### ISSUE TITLE
[ENH] - Add support for .ppt / .pptx

### ISSUE THREAD

**Issue by nenb** [Quansight/ragna#253]
### Feature description

(*Largely a copy/paste from #225*)

 Powerpoint documents are everywhere in the corporate world. We should support them out of the box. There are multiple Python packages out there that provide this functionality. We should do a light comparison of them to get a clearer picture. Optimally, we find a package that can give us page information. Not sure if that is possible in these data formats though.

### Value and/or benefit

Users with corporate documents will have a lower barrier of entry.

**Comment by pmeier** [comment]
Let's go for it!

**Comment by davidedigrande** [comment]
Hi!

I'd like to take this challenge as my first issue!

I have looked into issue #225 and #221 and I think the feature can be achieved using the library python-pptx which has similar API to python-docx, already used for #221

I've installed Ragna and looked at the codebase, but currently I can only work with RagnaDemo, as I don't have a vector DB or an API key for a LLM, but I think as long as we correctly define a `DocumentHandler` implementing 
- `requirements(cls) -> list[Requirement]:`
- `supported_suffixes(cls) -> list[str]`
- `extract_pages(self, document: Document) -> Iterator[Page]`

we should be fine, right? Of course I'll add testing and documentation.

Let me know if I can be assigned to this issue. Thanks!

**Comment by pmeier** [comment]
> I'd like to take this challenge as my first issue!

Hey Davide and welcome to Ragna :wave: Sure go ahead!

> I've installed Ragna and looked at the codebase, but currently I can only work with RagnaDemo, as I don't have a vector DB or an API key for a LLM

You can install local Vector DBS, i.e. Chroma and LanceDB. Either do it manually, `pip install`

https://github.com/Quansight/ragna/blob/61e8d5f6618d0533a106e5c27c350e2a2e71621e/pyproject.toml#L58-L59

or simply use the catch-all key `pip install -e '.[all]'`.

But yes, without an LLM API key, there is only the demo assistant for now.

> we should be fine, right? Of course I'll add testing and documentation.

Yes, that is sufficient. You can implement and test the document handler without having access to everything else.

**Comment by pmeier** [comment]
Closed in #296.
