### ISSUE TITLE
Don't reformat allowed document types in upload area

### ISSUE THREAD

**Issue by pmeier** [Quansight/ragna#271]
### Feature description

In the file selection area of the UI, we are currently dropping the leading period and uppercasing the extension of the allowed documents:

https://github.com/Quansight/ragna/blob/20ecade8992ecf458575a668a944b229e45e6f11/ragna/deploy/_ui/modal_configuration.py#L167-L169

Meaning, we are turning `.pdf` into `PDF`. This is in line with our [Figma designs](https://www.figma.com/file/9J5Vax4ENZCPQQMl8WamBq/Ragna?type=design&node-id=550-1345&mode=design&t=pCq14XC2jL09lG71-0).

Looking at this screenshot taken from #270

![image](https://github.com/Quansight/ragna/assets/6849766/b3313005-f2c7-42c3-840c-262559269e83)

I think TXT and PDF are clear enough, but I "stumbled" over `MD` as I have never seen that before. Had it been `.md`, I think it would be instantly clear for someone familiar with Markdown. Even if not, they could potentially perform the match when looking at the extension of the file in the file picker.

I want us to look at the design again and see if this was intentional or not. If no, I would like us to just use the plain extension including the leading period.

cc @smeragoel 

### Value and/or benefit

Less confusion about the possible file formats for the user. This becomes even more relevant if we add more formats in the future, which is planned.

**Comment by smeragoel** [comment]
Plain extensions, inlcuding leading periods are fine. Here's the updated design:

![image](https://github.com/Quansight/ragna/assets/98317216/85d101e0-87e8-45a3-b640-0a8ce1a91072)

I also changed the text a little bit to make it sound 'smoother'

**Comment by pmeier** [comment]
@smeragoel You can drop the `[max. 10MB]` from the design. We have a workaround in place and with that we are no longer limited in file size.

**Comment by smeragoel** [comment]
Fixed!
![image](https://github.com/Quansight/ragna/assets/98317216/761dc073-99c8-41b5-9133-ebd9940a7340)
