### ISSUE TITLE
Increase API timeout and add custom message

### ISSUE THREAD

**Issue by pmeier** [Quansight/ragna#277]
We have a timeout behavior in place when the API is started alongside the UI:

https://github.com/Quansight/ragna/blob/38f75f6d88e74f72c030ef50045315b81eb203aa/ragna/deploy/_cli/core.py#L132-L139

This is a good thing so the user doesn't waits forever for the UI to come up when it is actually the API that is failing to start. However 30 seconds, i.e. the default,

https://github.com/Quansight/ragna/blob/38f75f6d88e74f72c030ef50045315b81eb203aa/ragna/_utils.py#L76-L78

might be a little to low. We should bump to 60 seconds to avoid killing the UI when a slower box actually needs more time to start the API. Plus, we should have a custom message like "Failed to start the API" to make it more obvious what happened.

**Comment by smokestacklightnin** [comment]
@pmeier Does PR #299 accomplish what you were looking for? Thanks
