### ISSUE TITLE
Documentation for authentification objects is missing

### ISSUE THREAD

**Issue by pmeier** [Quansight/ragna#279]
#205 moved the `Authentication` object from `ragna.core` to `ragna.deploy`. However, the latter is not part of our API documentation:

https://github.com/Quansight/ragna/blob/38f75f6d88e74f72c030ef50045315b81eb203aa/docs/references/python-api.md?plain=1#L1-L7

In addition, `ragna.deploy` is also missing the block in the `__init__.py` file that hides our internal structure from the documentation. We can just copy the one from `ragna.core`

https://github.com/Quansight/ragna/blob/38f75f6d88e74f72c030ef50045315b81eb203aa/ragna/core/__init__.py#L57-L62

**Comment by kenudeh** [comment]
Hi. Was this `authentication` object documented while it was part of `ragna.core`? If it wasn't, then the need here is to document the content of the _authentication.py file? Is this correct?

**Comment by pmeier** [comment]
> Was this `authentication` object documented while it was part of `ragna.core`?

Yes, it was. We are automatically creating the API documentation with `mkdocstrings`

https://github.com/Quansight/ragna/blob/51fcda4f90460b8d60872d79cb251d2962e597e3/mkdocs.yml#L45-L56

Meaning, if a class or function is included in the `__all__` attribute of a module, e.g.

https://github.com/Quansight/ragna/blob/51fcda4f90460b8d60872d79cb251d2962e597e3/ragna/core/__init__.py#L1-L2

and given object has a docstring, e.g.

https://github.com/Quansight/ragna/blob/51fcda4f90460b8d60872d79cb251d2962e597e3/ragna/core/_components.py#L210-L211

This will automatically picked up when the documentation is built.

This was the case when the `Authentication` class was still part of `ragna.core`. But this missed when it was moved to `ragna.deploy`.
