### ISSUE TITLE
Add flag to disable unavailable components for the API / UI

### ISSUE THREAD

**Issue by pmeier** [Quansight/ragna#332]
As is, our official docker image has a problem: we do not include any builtin assistants:

https://github.com/Quansight/ragna/blob/b3cc95ab5b4228b03af9937afc9dc842ccf25432/ragna-docker.toml#L5-L13

The reason for this is that if we include them by default, we would force the user to supply API keys for all of them or otherwise the API / UI would fail to start.

However, from a UX perspective this is quite bad. Imagine I have an `OPENAI_API_KEY` and I want to run ragna with docker. The only way I currently have short of building my own image with a new config, is to set the assistants through an environment variable and thus overwrite the config:

```bash
$ docker run \
    -p 31476:31476 -p 31477:31477 \
    -e OPENAI_API_KEY=$OPENAI_API_KEY \
    -e RAGNA_COMPONENTS_ASSISTANTS='["ragna.assistants.Gpt4"]' \
    ragna
```

(Before #331 is fixed, the env var needs to be `RAGNA_CORE_ASSISTANTS`)

I propose we introduce a `--ignore-unavailable-components` (happy for naming help here). Instead of failing if a component is not available

https://github.com/Quansight/ragna/blob/b3cc95ab5b4228b03af9937afc9dc842ccf25432/ragna/core/_rag.py#L53-L56

just ignores the component. Of course we should still fail if no component is available.

This way we can put all of our builtin components in the config and the user can "activate" them by supplying the corresponding API key. Meaning, they can run

```bash
$ docker run ragna check
```

to see what API keys they can supply and afterwards run something like

```bash
$ docker run \
    -p 31476:31476 -p 31477:31477 \
    -e OPENAI_API_KEY=$OPENAI_API_KEY \
    ragna
```

to start the UI with the OpenAI assistants without selecting them by hand. Note that this would also select the gpt-3.5 variant automatically, while in the workaround above only gpt-4 would be available.

**Comment by dharhas** [comment]
+1 for making obvious things easy. i.e. most folks using the docker image will want things to just work and only needing to supply the API keys is a good approach for components we have already coded. 

It might be nice to also supply an undemanding local LLM instead of the DemoAssistant if we can find one that works on cpu.
