### ISSUE TITLE
Switching between chats is slow

### ISSUE THREAD

**Issue by nenb** [Quansight/ragna#337]
### Bug description

If I switch between chats multiple times, the UI performance becomes slower and slower. This effect is more extreme depending on the number of messages in a chat. For chats of over 20 messages, toggling between chats can make the UI unusable quite quickly on lower-end machines.

### How to reproduce the bug?

Create two chats of twenty+ messages. Toggle between the two chats a few times. It should take longer and longer to load the chat interface each time. The memory consumed should also be seen to grow steadily.

### Versions and dependencies used

`main` branch.

### Anything else?

The culprit is the `_stylesheets` [class variable](https://github.com/Quansight/ragna/blob/c1c159d196db99cb0372cddd4abf8ecee3ce255d/ragna/deploy/_ui/central_view.py#L161) in `RagnaChatMessage`. 

For each message created, this class variable grows in size. Multiple messages are (re-)created when toggling between chats, causing this class variable to quickly explode in size. This is causing `panel` to do a bunch of work under the hood, which quickly degrades the UI performance.

This is likely best dealt with in #312, to make sure that similar effects don't creep in elsewhere.

(Also happy to open a small PR resolving this if this is easier.)

**Comment by pmeier** [comment]
This was first reported in #239 although without any indication of what is wrong. Thanks for debugging @nenb!

> This is likely best dealt with in #312, to make sure that similar effects don't creep in elsewhere.
> 
> (Also happy to open a small PR resolving this if this is easier.)

#312 hinges on `panel==1.4.0`, which is not released yet (https://github.com/Quansight/ragna/pull/312#discussion_r1481492621). Happy to review a workaround in the meantime.

**Comment by nenb** [comment]
> Happy to review a workaround in the meantime.

I've opened a quick PR in #341. This **does not** prevent future regressions, as I didn't have time to think of a way to do this. This is potentially relevant to #312.
