### ISSUE TITLE
ModuleNotFoundError: No module named 'documentation_helpers'

### ISSUE THREAD

**Issue by pieterjanvc** [Quansight/ragna#373]
### Bug description

Following the [tutorial](https://ragna.chat/en/stable/generated/tutorials/gallery_rest_api/#download_links), I'm stuck at the first code block at the line
```
import documentation_helpers
```
I pip installed ragna successfully

### How to reproduce the bug?

If I run this in python 3.10.12 on Ubuntu
```
import documentation_helpers
```
I get
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'documentation_helpers'
```

### Versions and dependencies used

Python 2.10.12
Ragna ragna 0.2.0
Ubuntu 22.04.2 LTS

**Comment by pmeier** [comment]
The module you are looking for is [here](https://github.com/Quansight/ragna/blob/main/docs/documentation_helpers.py), but is not distributed with Ragna as it is only needed for the documentation. Could you tell us how you are interacting with the tutorial?

In the REST API tutorial there are two blocks  that require the `documentation_helpers`:

1. To launch the REST API

   https://github.com/Quansight/ragna/blob/aa2a70263b373baaf40b4c41701c850e40873ad9/docs/tutorials/gallery_rest_api.py#L50-L51

   We explain above that outside of the documentation you would do this from another terminal

   https://github.com/Quansight/ragna/blob/aa2a70263b373baaf40b4c41701c850e40873ad9/docs/tutorials/gallery_rest_api.py#L22-L30

2. To upload a test document

   https://github.com/Quansight/ragna/blob/aa2a70263b373baaf40b4c41701c850e40873ad9/docs/tutorials/gallery_rest_api.py#L101-L104

   You can find this document [here](https://github.com/Quansight/ragna/blob/main/docs/assets/ragna.txt), but you could also use any other document.

**Comment by pmeier** [comment]
One option for us could be to just move the documentation helpers into `ragna._docs`. That way

1. we don't need to have extra files in the documentation that need to be included through `sys.path`, reducing the noise in the example
2. users can run the examples if they have Ragna installed
3. we are keeping the advantage of not being bound to BC compatibility even after we adopt [semantic versioning](https://github.com/Quansight/ragna/blob/main/docs/install.md#backwards-compatibility) given that the module is private.

I guess we could also ship the `ragna.txt` file given that it is not large.

**Comment by pmeier** [comment]
> I'd be really happy to assist the project try doing that & contribute to it further 🙂.

Hi @arjxn-py :wave: We would love to have your contribution here. If you send a PR, tag me there so I can review it.

**Comment by pmeier** [comment]
@arjxn-py do you have a timeline for your contribution? I want to push a small bug fix release soon and this should be included.

**Comment by arjxn-py** [comment]
> @arjxn-py do you have a timeline for your contribution? I want to push a small bug fix release soon and this should be included.

Apologies for the delay in response, I plan to fix this asap. I'm creating a branch & opening a PR to track progress in the meantime.
