### ISSUE TITLE
CopytoClipboardButton does not work when streaming

### ISSUE THREAD

**Issue by nenb** [Quansight/ragna#408]
### Bug description

When I try to copy a response to the clipboard when streaming, at most 1 letter seems to be selected.

It appears to work correctly when using the demo assistants (where there is no streaming).

### How to reproduce the bug?

Select an assistant that involves streaming and try to copy the response with the button.

### Anything else?

The logic is contained in `central_view.py`. A ReactiveHTML component is created for `CopyToClipboardButton`. I think that when we are streaming, we are not passing the full value to this component.

**Comment by pmeier** [comment]
I don't think we have ever selected a correct behavior here. I think there are two options:

1. Copy whatever message fragment is already there
2. Disable the copy button until streaming is done and afterwards copy the whole message

Of those two I would prefer 2. But we should look around how others, i.e. OpenAI / Anthropic / ..., handle this. No need to diverge here if there is an established behavior.

**Comment by nenb** [comment]
@pmeier OpenAI follow 2. I would also prefer 2 for performance reasons with `panel`.

I can open a short PR later if 2 is okay.
