### ISSUE TITLE
chat bubble cannot be loaded

### ISSUE THREAD

**Issue by pmeier** [Quansight/ragna#415]
### Bug description

Chat bubble icon in left side bar is missing

![image](https://github.com/Quansight/ragna/assets/6849766/75e58bee-7242-42ef-a832-798cd0266dea)

This was broken in #312. Previously it looked like

![image](https://github.com/Quansight/ragna/assets/6849766/33e7f0d2-2620-4df9-9a9e-9f5a82951ab9)

The problem is the relative link in https://github.com/Quansight/ragna/blob/0cb205f24ca9fb322ac32a2e1aaec6b34928cd2e/ragna/deploy/_ui/css/left_sidebar/button.css#L27

Since we are currently in `/css/left_sidebar`, it looks for `/css/left_sidebar/imgs/chat_bubble.svg` and fails.

### How to reproduce the bug?

Open the web UI and look at the left sidebar

### Versions and dependencies used

`main` after #312

### Anything else?

This can be fixed by using `url("../../imgs/chat_bubble.svg")`, but I don't know if that is the best way to do it.

**Comment by pierrotsmnrd** [comment]
Using `url("../../imgs/chat_bubble.svg")` is a fair way to have it working. Another solution is to have the image base64-encoded in the CSS, but we don't want that.
