### ISSUE TITLE
Automating Workflow for Docker Requirement Fixes

### ISSUE THREAD

**Issue by arjxn-py** [Quansight/ragna#458]
Currently, the `docker-requirements / update (pull_request)` workflow is configured to be triggered manually. When activated, it opens a separate PR to fix Docker requirements. While this ensures updates are controlled, it requires manual intervention, which can delay necessary fixes.

Maybe we can configure the workflow to be automatically triggered on every push to the main branch, creating a PR if Docker requirements need fixing. cc: @pmeier

**Comment by arjxn-py** [comment]
> Maybe we can configure the workflow to be automatically triggered on every push to the main branch, creating a PR if Docker requirements need fixing.

You have my +1 for this, I'd be happy to configure it however we decide.

**Comment by pmeier** [comment]
Two comments from my side:

1. I'm ok with running this on `main`, but in that case we should disable the old triggers. It makes little sense to run this on a PR. Whether it comes out red or green, it will be re-run after merge anyway and thus the information gain is minimal.
2. We might need some logic to figure out how to ping on the PR. It should be the person who merged the PR and potentially the author of the PR as well. I think we need to hit the GH API for that.

But in any case, I think we can move forward @arjxn-py!
